export const PAGE_ROUTES = {
    signIn:"/sign-in",
    signUp:"/sign-up",
    home:"/home",
    products:{
        sectionParams:"/products/:section",
        productParams:"/products/:section/:id",
        all:"/products/all",
        guitars:"/products/guitars",
        basses:"/products/basses",
        violins:"/products/violins",
        pianos:"/products/pianos",
        saxophones:"/products/saxophones",
        trumpets:"/products/trumpets",
        flutes:"/products/flutes",
        clarinets:"/products/clarinets",
    },
    favorites:"/favorites",
    cart:"/cart"
}